### ISSUE TITLE
Unable to run test 

### ISSUE THREAD

**Issue by chintan9** [qawolf/qawolf#397]
```
npx qawolf test
npx jest --config={} --preset="@qawolf/jest-plugin" --rootDir=.qawolf --testTimeout=60000

● Validation Error:

  Preset @qawolf/jest-plugin is invalid:

  The "id" argument must be of type string. Received type object
  TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type object
    at validateString (internal/validators.js:112:11)
    at Module.require (internal/modules/cjs/loader.js:841:3)
    at require (internal/modules/cjs/helpers.js:74:18)
    at setupPreset (/Users/cprajapa/Playground/QAWolfDemo/node_modules/jest-config/build/normalize.js:298:14)
    at normalize (/Users/cprajapa/Playground/QAWolfDemo/node_modules/jest-config/build/normalize.js:643:15)
    at readConfig (/Users/cprajapa/Playground/QAWolfDemo/node_modules/jest-config/build/index.js:220:68)
    at readConfigs (/Users/cprajapa/Playground/QAWolfDemo/node_modules/jest-config/build/index.js:401:32)
    at runCLI (/Users/cprajapa/Playground/QAWolfDemo/node_modules/@jest/core/build/cli/index.js:204:29)
    at Object.run (/Users/cprajapa/Playground/QAWolfDemo/node_modules/jest/node_modules/jest-cli/build/cli/index.js:216:62)
    at Object.<anonymous> (/Users/cprajapa/Playground/QAWolfDemo/node_modules/jest/node_modules/jest-cli/bin/jest.js:16:27)

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html

```

**Comment by jperl** [comment]
Can you please run: npm ci

That should reinstall node modules with a clean slate.

Also is this a new or existing project? If it is an existing project, what version of Jest are you using?

**Comment by chintan9** [comment]
Still same thing happening 

> Can you please run: npm ci
> That should reinstall node modules with a clean slate.
Done


> Also is this a new or existing project? If it is an existing project, what version of Jest are you using?
New Project

**Comment by jperl** [comment]
Thank you for that information. I am traveling now, but I will look into it as soon as I get back tonight.

**Comment by chintan9** [comment]
@jperl  Thanks 

 When I used below script that work well for me
npx jest --config={} --rootDir=.qawolf --testTimeout=60000

**Comment by jperl** [comment]
This plugin is not essential, but it is nice to have. It does these things:

- stops the test on first failed step
- logs in your browser the test name, at the beginning of each test

-----

This error says that Jest is unable to find our plugin: `@qawolf/jest-plugin`.

1. Is your directory running on a [Windows network mapped folder](https://github.com/facebook/jest/issues/8763)? Unfortunately Jest seems to have a problem with those.

2. Can you check that your `node_modules/` installed the plugin.  If so you should find this folder `node_modules/@qawolf/jest-plugin` under your project.

**Comment by chintan9** [comment]
@jperl  Adding below command works for me.

```npm install --save-dev @qawolf/jest-plugin```

**Comment by jperl** [comment]
Ok great, I will close this issue for now. Perhaps it was a problem with a package-lock file. If someone else encounters this issue I will re-open and try a deeper investigation.
