### ISSUE TITLE
Minimum node version for npm init qawolf

### ISSUE THREAD

**Issue by arjun27** [qawolf/qawolf#536]
It seems `npm init qawolf` requires node 11+. Fails on node 10.16, with this error:

```
➜  qawolf-try npm init qawolf
npx: installed 67 in 4.167s
(node:75833) ExperimentalWarning: The fs.promises API is experimental

(node:75833) UnhandledPromiseRejectionWarning: TypeError: [view(...)].flat is not a function
    at workLoop (/Users/arjun/.npm/_npx/75788/lib/node_modules/create-qawolf/node_modules/@inquirer/core/hooks.js:116:47)
(node:75833) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:75833) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

(node:75833) UnhandledPromiseRejectionWarning: TypeError: [view(...)].flat is not a function
    at workLoop (/Users/arjun/.npm/_npx/75788/lib/node_modules/create-qawolf/node_modules/@inquirer/core/hooks.js:116:47)
    at handleChange (/Users/arjun/.npm/_npx/75788/lib/node_modules/create-qawolf/node_modules/@inquirer/core/hooks.js:115:30)
    at newValue (/Users/arjun/.npm/_npx/75788/lib/node_modules/create-qawolf/node_modules/@inquirer/core/hooks.js:31:7)
    at useKeypress (/Users/arjun/.npm/_npx/75788/lib/node_modules/create-qawolf/node_modules/@inquirer/input/index.js:23:7)
    at ReadStream.handler (/Users/arjun/.npm/_npx/75788/lib/node_modules/create-qawolf/node_modules/@inquirer/core/hooks.js:40:5)
    at ReadStream.emit (events.js:203:15)
    at emitKeys (internal/readline.js:424:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (readline.js:1075:36)
    at ReadStream.emit (events.js:198:13)
(node:75833) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
/Users/arjun/.npm/_npx/75788/lib/node_modules/create-qawolf/node_modules/@inquirer/core/hooks.js:116
        screen.render(...[view(config, done)].flat().filter(Boolean));
                                              ^

TypeError: [view(...)].flat is not a function
    at workLoop (/Users/arjun/.npm/_npx/75788/lib/node_modules/create-qawolf/node_modules/@inquirer/core/hooks.js:116:47)
    at handleChange (/Users/arjun/.npm/_npx/75788/lib/node_modules/create-qawolf/node_modules/@inquirer/core/hooks.js:115:30)
    at newValue (/Users/arjun/.npm/_npx/75788/lib/node_modules/create-qawolf/node_modules/@inquirer/core/hooks.js:31:7)
    at Timeout.setTimeout (/Users/arjun/.npm/_npx/75788/lib/node_modules/create-qawolf/node_modules/@inquirer/core/lib/prefix.js:11:9)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
➜  qawolf-try
➜  qawolf-try nvm ls
       v0.10.48
         v8.0.0
         v8.3.0
        v8.12.0
        v9.11.1
       v10.13.0
->     v10.16.0
        v11.2.0
       v11.15.0
         system
```

**Comment by jperl** [comment]
Thanks I'll fix this ASAP.

**Comment by jperl** [comment]
@arjun27 This should now be fixed. Please try with `npm init qawolf@latest`.
