### ISSUE TITLE
TypeError: this._context.exposeBinding is not a function

### ISSUE THREAD

**Issue by Banou26** [qawolf/qawolf#739]
Since i upgraded to the `1.2.1` from `1.0.1`, when trying to use `await qawolf.create();`, this error is thrown:
```
TypeError: this._context.exposeBinding is not a function

      at ContextEventCollector._emitEvents (../node_modules/qawolf/src/create-code/ContextEventCollector.ts:32:25)
      at Function.create (../node_modules/qawolf/src/create-code/ContextEventCollector.ts:18:21)
      at Function.create (../node_modules/qawolf/src/create-code/CreateManager.ts:29:51)
      at Object.exports.create (../node_modules/qawolf/src/create-code/create.ts:55:19)
```
There is the `// 🐺 create code here` still appended to the code though.

**Comment by jperl** [comment]
@Banou26 Make sure to upgrade playwright to 1.2.1 as well.
