### ISSUE TITLE
[Feature] macOS Big Sur support

### ISSUE THREAD

**Issue by diogopaulino** [qawolf/qawolf#852]
## Issue Description

Hi! We realized that qawolf does not support the new Macos Big Sur 😞 

The playwright has been updated to correct this problem, but it also needs to update the qawolf dependency.

<img width="1124" alt="Screen Shot 2020-11-17 at 07 35 30" src="https://user-images.githubusercontent.com/1030809/99379480-7e630480-28a7-11eb-889f-de9e05950691.png">

### What version of QA Wolf are you using?
qawolf v1.4.0

### Errors
```
Projects/greyhound/node_modules/playwright/lib/server/browserType.js
throw new Error('Browser is not supported on current platform');

Error: Browser is not supported on current platform
    at Chromium.executablePath (/Users/diogo.paulino/Documents/Projects/greyhound/node_modules/playwright/lib/server/browserType.js:48:19)
    at new BrowserTypeDispatcher (/Users/diogo.paulino/Documents/Projects/greyhound/node_modules/playwright/lib/dispatchers/browserTypeDispatcher.js:25:41)
    at new PlaywrightDispatcher (/Users/diogo.paulino/Documents/Projects/greyhound/node_modules/playwright/lib/dispatchers/playwrightDispatcher.js:30:23)
    at setupInProcess (/Users/diogo.paulino/Documents/Projects/greyhound/node_modules/playwright/lib/inprocess.js:33:5)
    at Object.<anonymous> (/Users/diogo.paulino/Documents/Projects/greyhound/node_modules/playwright/index.js:20:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
error Command failed with exit code 1.
```

### Steps to Reproduce
Run integration test in MacOS Big Sur

## Possible Solution
Upgrade playwright to latest version
https://github.com/microsoft/playwright/issues/2789

## Information About Your System

- macOS Big
- qawolf v1.4.0

**Comment by jperl** [comment]
Thanks for reporting. We have been hard at work on QA Wolf 2.0 and plan to open source it soon, That is why you have not seen too much activity on this repo.

In the meantime, we will do a minor release for qawolf to upgrade playwright & fix this issue.

**Comment by diogopaulino** [comment]
Thank you for that! We look forward to it! @jperl

**Comment by jperl** [comment]
This should work now with qawolf@1.6.0.

**Comment by diogopaulino** [comment]
Nice @jperl! Thank u!
